-- 客户服务运营 P0：预约、员工外出、跟进与统一活动回放。
-- 边界：不修改渠道合作、银行产品、匹配或审批表。

CREATE TABLE IF NOT EXISTS `t_client_appointment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键，不对外暴露',
  `appointment_no` varchar(64) NOT NULL COMMENT '预约业务编号',
  `client_code` varchar(64) NOT NULL COMMENT '客户业务编号',
  `order_no` varchar(64) DEFAULT NULL COMMENT '关联服务工单号',
  `host_staff_code` varchar(32) NOT NULL COMMENT '服务顾问工号',
  `appointment_type` varchar(32) NOT NULL COMMENT 'COMPANY_ON_SITE/HOME_VISIT/VIDEO_MEETING/PHONE_CONSULT',
  `scheduled_start` datetime NOT NULL COMMENT '预约开始时间',
  `scheduled_end` datetime NOT NULL COMMENT '预约结束时间',
  `location_name` varchar(128) DEFAULT NULL COMMENT '客户可见地点名称',
  `location_detail` varchar(255) DEFAULT NULL COMMENT '客户可见地点详情或会议说明',
  `status` varchar(16) NOT NULL DEFAULT 'REQUESTED' COMMENT 'REQUESTED/CONFIRMED/ARRIVED/SERVING/COMPLETED/CANCELLED/NO_SHOW/RESCHEDULED',
  `customer_confirm_status` varchar(16) NOT NULL DEFAULT 'PENDING' COMMENT 'PENDING/CONFIRMED；员工代建同样保留客户确认状态',
  `actual_arrived_at` datetime DEFAULT NULL COMMENT '公司现场实际到店时间',
  `actual_left_at` datetime DEFAULT NULL COMMENT '实际结束或离店时间',
  `cancel_reason` varchar(500) DEFAULT NULL COMMENT '取消或异常调整原因',
  `customer_visible_note` varchar(500) DEFAULT NULL COMMENT '客户可见说明及下一步安排',
  `internal_note` varchar(1000) DEFAULT NULL COMMENT '仅员工可见备注',
  `created_by_type` varchar(16) NOT NULL COMMENT 'CUSTOMER/STAFF',
  `created_by_code` varchar(64) NOT NULL COMMENT '创建人业务编号',
  `source_terminal` varchar(16) NOT NULL COMMENT 'WEB/MINI_APP/H5',
  `rescheduled_from_no` varchar(64) DEFAULT NULL COMMENT '改期来源预约号；原记录保留为RESCHEDULED',
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_appointment_no` (`appointment_no`),
  KEY `idx_appointment_client_time` (`client_code`,`scheduled_start`),
  KEY `idx_appointment_staff_status_time` (`host_staff_code`,`status`,`scheduled_start`),
  KEY `idx_appointment_day_type_status` (`scheduled_start`,`appointment_type`,`status`),
  KEY `idx_appointment_rescheduled_from` (`rescheduled_from_no`),
  CONSTRAINT `chk_appointment_type` CHECK (`appointment_type` IN ('COMPANY_ON_SITE','HOME_VISIT','VIDEO_MEETING','PHONE_CONSULT')),
  CONSTRAINT `chk_appointment_status` CHECK (`status` IN ('REQUESTED','CONFIRMED','ARRIVED','SERVING','COMPLETED','CANCELLED','NO_SHOW','RESCHEDULED')),
  CONSTRAINT `chk_appointment_creator_type` CHECK (`created_by_type` IN ('CUSTOMER','STAFF')),
  CONSTRAINT `chk_appointment_terminal` CHECK (`source_terminal` IN ('WEB','MINI_APP','H5')),
  CONSTRAINT `chk_appointment_time` CHECK (`scheduled_end` > `scheduled_start`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户预约与四类服务履约记录';

CREATE TABLE IF NOT EXISTS `t_staff_outing` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键，不对外暴露',
  `outing_no` varchar(64) NOT NULL COMMENT '外出业务编号',
  `staff_code` varchar(32) NOT NULL COMMENT '外出员工工号',
  `client_code` varchar(64) NOT NULL COMMENT '关联客户业务编号',
  `appointment_no` varchar(64) NOT NULL COMMENT '关联上门预约号',
  `order_no` varchar(64) DEFAULT NULL COMMENT '关联服务工单号',
  `outing_type` varchar(32) NOT NULL DEFAULT 'HOME_VISIT' COMMENT '第一版固定HOME_VISIT',
  `planned_start` datetime NOT NULL,
  `planned_end` datetime NOT NULL,
  `actual_departed_at` datetime DEFAULT NULL COMMENT '出发打卡时间',
  `departed_location_ciphertext` varchar(1024) DEFAULT NULL COMMENT '出发单点定位加密载荷（经纬度/精度/位置文本/采集时间）',
  `actual_returned_at` datetime DEFAULT NULL COMMENT '返回打卡时间',
  `returned_location_ciphertext` varchar(1024) DEFAULT NULL COMMENT '返回单点定位加密载荷（经纬度/精度/位置文本/采集时间）',
  `destination` varchar(255) NOT NULL COMMENT '拜访目的地',
  `purpose` varchar(500) NOT NULL COMMENT '拜访目的',
  `status` varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT 'DRAFT/READY/IN_PROGRESS/COMPLETED/CANCELLED',
  `internal_note` varchar(1000) DEFAULT NULL,
  `created_by` varchar(64) DEFAULT NULL,
  `updated_by` varchar(64) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_outing_no` (`outing_no`),
  UNIQUE KEY `uk_outing_appointment` (`appointment_no`),
  KEY `idx_outing_staff_status_time` (`staff_code`,`status`,`planned_start`),
  KEY `idx_outing_client_time` (`client_code`,`planned_start`),
  CONSTRAINT `chk_outing_type` CHECK (`outing_type` = 'HOME_VISIT'),
  CONSTRAINT `chk_outing_status` CHECK (`status` IN ('DRAFT','READY','IN_PROGRESS','COMPLETED','CANCELLED')),
  CONSTRAINT `chk_outing_time` CHECK (`planned_end` > `planned_start`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='员工上门拜访外出与双打卡记录（无审批、无连续轨迹）';

CREATE TABLE IF NOT EXISTS `t_client_follow_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键，不对外暴露',
  `follow_no` varchar(64) NOT NULL COMMENT '跟进业务编号',
  `client_code` varchar(64) NOT NULL COMMENT '客户业务编号',
  `order_no` varchar(64) DEFAULT NULL COMMENT '可选关联服务工单',
  `appointment_no` varchar(64) DEFAULT NULL COMMENT '可选关联预约',
  `staff_code` varchar(32) NOT NULL COMMENT '跟进员工工号',
  `channel_type` varchar(24) NOT NULL COMMENT 'PHONE/COMPANY_ON_SITE/HOME_VISIT/VIDEO_MEETING/WECOM/OTHER',
  `result_code` varchar(32) NOT NULL COMMENT '已联系/待补材料/已预约/已到店/暂缓/无意向等字典编码',
  `content` text NOT NULL COMMENT '内部跟进内容',
  `customer_visible_summary` varchar(500) DEFAULT NULL COMMENT '经裁剪的客户可见摘要',
  `next_action` varchar(500) DEFAULT NULL COMMENT '下一步动作',
  `next_follow_at` datetime DEFAULT NULL COMMENT '下次跟进时间',
  `visibility` varchar(16) NOT NULL DEFAULT 'STAFF_ONLY' COMMENT 'STAFF_ONLY/CUSTOMER',
  `created_by` varchar(64) DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_follow_no` (`follow_no`),
  KEY `idx_follow_client_time` (`client_code`,`created_at`),
  KEY `idx_follow_staff_next` (`staff_code`,`next_follow_at`),
  CONSTRAINT `chk_follow_visibility` CHECK (`visibility` IN ('STAFF_ONLY','CUSTOMER')),
  CONSTRAINT `chk_follow_channel` CHECK (`channel_type` IN ('PHONE','COMPANY_ON_SITE','HOME_VISIT','VIDEO_MEETING','WECOM','OTHER'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户级跟进记录；不依赖工单存在';

CREATE TABLE IF NOT EXISTS `t_client_activity_event` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '物理主键，不对外暴露',
  `event_no` varchar(64) NOT NULL COMMENT '活动事件业务编号',
  `client_code` varchar(64) NOT NULL COMMENT '客户业务编号',
  `staff_code` varchar(32) DEFAULT NULL COMMENT '关联员工工号',
  `event_type` varchar(32) NOT NULL COMMENT '画像/材料/报告/跟进/预约/到店/外出/工单事件',
  `source_type` varchar(32) NOT NULL COMMENT '原始业务对象类型',
  `source_no` varchar(64) NOT NULL COMMENT '原始业务对象编号',
  `happened_at` datetime NOT NULL COMMENT '业务发生时间',
  `summary` varchar(500) NOT NULL COMMENT '事件摘要',
  `visibility` varchar(16) NOT NULL DEFAULT 'STAFF_ONLY' COMMENT 'STAFF_ONLY/CUSTOMER',
  `actor_type` varchar(16) NOT NULL COMMENT 'CUSTOMER/STAFF/SYSTEM',
  `actor_code` varchar(64) NOT NULL COMMENT '操作者业务编号',
  `metadata_json` json DEFAULT NULL COMMENT '裁剪后的扩展数据；禁止写银行准入或内部匹配结果到客户事件',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_activity_event_no` (`event_no`),
  KEY `idx_activity_client_time` (`client_code`,`happened_at`),
  KEY `idx_activity_source` (`source_type`,`source_no`),
  KEY `idx_activity_staff_time` (`staff_code`,`happened_at`),
  CONSTRAINT `chk_activity_visibility` CHECK (`visibility` IN ('STAFF_ONLY','CUSTOMER')),
  CONSTRAINT `chk_activity_actor_type` CHECK (`actor_type` IN ('CUSTOMER','STAFF','SYSTEM'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户服务统一活动回放读模型（追加写）';
