"""当前项目 Web 菜单权限矩阵唯一真源（用于审计，不直接连接数据库）。"""

ROLES = ("CHANNEL", "ADVISER", "DEPT_MANAGER", "OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER")

MENUS = {
    "/workbench": {"name": "工作台", "domain": "工作台", "roles": set(ROLES)},
    "/lead/my": {"name": "我的线索", "domain": "客户中心", "roles": set(ROLES)},
    "/lead/pool": {"name": "线索公海", "domain": "客户中心", "roles": set(ROLES) - {"CHANNEL"}},
    "/client/my": {"name": "我的客户", "domain": "客户中心", "roles": {"CHANNEL", "ADVISER", "DEPT_MANAGER", "OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/client/team": {"name": "团队客户", "domain": "客户中心", "roles": {"DEPT_MANAGER"}},
    "/client/company": {"name": "全司客户", "domain": "客户中心", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/client/company-sea": {"name": "客户公海", "domain": "客户中心", "roles": set(ROLES) - {"CHANNEL"}},
    "/client/team-sea": {"name": "团队公海", "domain": "客户中心", "roles": {"DEPT_MANAGER"}},
    "/client-lookup": {"name": "客户检索", "domain": "客户中心", "roles": set(ROLES) - {"CHANNEL"}},
    "/ocr": {"name": "客户材料", "domain": "客户中心", "roles": set(ROLES) - {"CHANNEL"}},
    "/screening": {"name": "匹配任务", "domain": "智能匹配", "roles": set(ROLES) - {"CHANNEL"}},
    "/report/screening": {"name": "诊断报告", "domain": "智能匹配", "roles": set(ROLES)},
    "/service-operations/daily": {"name": "今日服务台", "domain": "服务交付", "roles": set(ROLES) - {"CHANNEL"}},
    "/service-operations/appointments": {"name": "客户预约", "domain": "服务交付", "roles": set(ROLES) - {"CHANNEL"}},
    "/service-operations/outings": {"name": "员工外出", "domain": "服务交付", "roles": set(ROLES) - {"CHANNEL"}},
    "/service-operations/replay": {"name": "客户回放", "domain": "服务交付", "roles": set(ROLES) - {"CHANNEL"}},
    "/order": {"name": "服务工单", "domain": "服务交付", "roles": set(ROLES) - {"CHANNEL"}},
    "/approval/mine": {"name": "我的申请", "domain": "审批中心", "roles": {"ADVISER", "DEPT_MANAGER", "OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/approval/download": {"name": "附件下载审核", "domain": "审批中心", "roles": {"DEPT_MANAGER", "OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/approval/allocation": {"name": "客户分配审核", "domain": "审批中心", "roles": {"DEPT_MANAGER", "OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/approval/product": {"name": "产品审核", "domain": "审批中心", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/approval/outing": {"name": "外出审批", "domain": "审批中心", "roles": {"DEPT_MANAGER", "OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/approval/channel-lead": {"name": "渠道线索审核", "domain": "审批中心", "roles": {"BOSS", "SUPER_ADMIN", "SUPER"}},
    "/approval/sms-template": {"name": "短信模板审核", "domain": "审批中心", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/approval/report-template": {"name": "报告模板审核", "domain": "审批中心", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/sms/templates": {"name": "短信模板", "domain": "营销激励", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/sms/records": {"name": "发送记录", "domain": "营销激励", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/reward/records": {"name": "奖励发放", "domain": "营销激励", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/reward/rules": {"name": "奖励规则", "domain": "营销激励", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/report/center": {"name": "经营概览", "domain": "经营分析", "roles": set(ROLES) - {"CHANNEL"}},
    "/report/trend": {"name": "趋势分析", "domain": "经营分析", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/report-template": {"name": "报告模板", "domain": "经营分析", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/product/all": {"name": "全量产品库", "domain": "产品与规则", "roles": set(ROLES)},
    "/product/cooperate": {"name": "合作产品库", "domain": "产品与规则", "roles": {"BOSS", "SUPER_ADMIN", "SUPER"}},
    "/channel-config": {"name": "渠道管理", "domain": "产品与规则", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/rule-template": {"name": "规则模板", "domain": "产品与规则", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/rule": {"name": "规则实例", "domain": "产品与规则", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/strategy-template": {"name": "策略方案", "domain": "产品与规则", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/plan-edit": {"name": "执行计划", "domain": "产品与规则", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/blacklist": {"name": "风控名单", "domain": "系统管理", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/audit": {"name": "审计日志", "domain": "系统管理", "roles": {"OPERATOR", "BOSS", "SUPER_ADMIN", "SUPER"}},
    "/org/staff": {"name": "员工管理", "domain": "系统管理", "roles": {"OPERATOR", "SUPER_ADMIN", "SUPER"}},
    "/org/roles": {"name": "角色权限", "domain": "系统管理", "roles": {"OPERATOR", "SUPER_ADMIN", "SUPER"}},
    "/org/api-permissions": {"name": "接口权限", "domain": "系统管理", "roles": {"OPERATOR", "SUPER_ADMIN", "SUPER"}},
    "/config-wizard": {"name": "系统配置", "domain": "系统管理", "roles": {"OPERATOR", "SUPER_ADMIN", "SUPER"}},
    "/debug": {"name": "调试中心", "domain": "系统管理", "roles": {"SUPER_ADMIN", "SUPER"}},
}

def role_paths(role):
    return {path for path, item in MENUS.items() if role in item["roles"]}
